// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GymFlowProDbContext))]
    [Migration("20260827180000_AddStaffNotificationInboxFields")]
    partial class AddStaffNotificationInboxFields
    {
    }
}
