namespace GMS.Core.Entities;

/// <summary>
/// Pre-computed analytics snapshot per tenant per day.
/// Generated by the AnalyticsAggregationJob at midnight Cairo time.
/// Used for dashboard KPIs without expensive real-time queries.
/// </summary>
public class GymAnalyticsSnapshot : BaseEntity
{
    public Guid TenantId { get; set; }

    /// <summary>Date this snapshot covers (UTC date).</summary>
    public DateOnly SnapshotDate { get; set; }

    // Member KPIs
    public int ActiveMembers { get; set; }
    public int ExpiredMembers { get; set; }
    public int FrozenMembers { get; set; }
    public int NewMembersThisMonth { get; set; }

    // Revenue KPIs
    public decimal RevenueThisMonth { get; set; }
    public string Currency { get; set; } = "EGP";

    // Attendance KPIs
    public int CheckinsToday { get; set; }
    public int CheckinsThisMonth { get; set; }

    // Invitation KPIs
    public int InvitationsSentThisMonth { get; set; }
    public int InvitationsConvertedThisMonth { get; set; }

    // Navigation
    public Tenant? Tenant { get; set; }
}
