<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\..\GMS.Api\hymotion.ico</ApplicationIcon>
    <AssemblyName>HyMotionSetup</AssemblyName>
    <RootNamespace>HyMotion.Desktop</RootNamespace>
    <ApplicationManifest>..\Shared\asInvoker.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.2.0</Version>
    <Product>HyMotion Setup</Product>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" Link="Shared\%(Filename).cs" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
</Project>
